### ISSUE TITLE
トップページのデザイン微調整【優先度：高（最優先！）】

### ISSUE THREAD

**Issue by eggsystem** [egg-system/corporate-site#100]
添付ファイルのように修正する。

基本的には soup stockのデザインと同じにする。
微妙に真似る、ではなく、全く同じにする。（←大事）

【追加】
「最近の活動・コラム」「わたしたちについて」「x-faCEの強み」などのタイトルの文字の大きさが統一されていないので、同じにする。

![トップページ修正点](https://user-images.githubusercontent.com/38577320/79632220-fc87ed00-8198-11ea-8b63-9cfe89854d04.png)

**Comment by tomo-ogiso** [comment]
@eggsystem 
soup stockのデザインはどちらでしょうか？

**Comment by tomo-ogiso** [comment]
@eggsystem 
修正しました。確認よろしくお願い致します。

**Comment by tomo-ogiso** [comment]
@eggsystem 
修正しました。確認よろしくお願い致します。

**Comment by tomo-ogiso** [comment]
@eggsystem 
修正しました。確認よろしくお願い致します。

**Comment by tomo-ogiso** [comment]
@eggsystem 
こちらcloseします。

**Comment by tomo-ogiso** [comment]
@eggsystem 
すみません間違えてIssueをcloseしてしまいました。。

**Comment by tomo-ogiso** [comment]
closeします。
