### ISSUE TITLE
文字間隔の調整をする【優先度：高（最優先！）】

### ISSUE THREAD

**Issue by eggsystem** [egg-system/corporate-site#102]
英字の文字間隔が詰まりすぎているので、もう少しゆとりをもたせるようにする。
soup stockと同じ文字間隔にする。

* 対象
全ページ

**Comment by tomo-ogiso** [comment]
@eggsystem 
soup stockとはどちらでしょうか？

**Comment by eggsystem** [comment]
@tomo-ogiso @tada00 
これってTDが対応済？？
対応済だったら、masterへマージしておいて欲しい！

以前確認したような気がする。。

**Comment by tada00** [comment]
@eggsystem 
対応済みです！
マージします
