### ISSUE TITLE
トップページのコラム欄の画像サイズを調整する【優先度：高（最優先！）】

### ISSUE THREAD

**Issue by eggsystem** [egg-system/corporate-site#104]
<img width="1278" alt="スクリーンショット 2020-04-19 16 26 48" src="https://user-images.githubusercontent.com/38577320/79682099-9b285280-825a-11ea-888a-b4bf6208f2d0.png">

画像サイズによってレイアウトがずれちゃうので、画像の縮尺比率は変えずに、レイアウトが揃うように調整する。

画像自体が縦に伸びたり、横に伸びたり、しないように要注意。

**Comment by tomo-ogiso** [comment]
@eggsystem 
プルしたら画像が差し込まれていないのですが・・・。
imageに対して適切な高さを指定してあげるイメージで合っておりますか？？

**Comment by eggsystem** [comment]
@tomo-ogiso 
記事によって若干画像サイズが異なるんですけど、縦幅が揃うようにして欲しいです！

**Comment by tomo-ogiso** [comment]
@eggsystem 
レスポンス遅くなってしまい申し訳ございません。
プルしたものだとコラムに画像がないのですが、
画像が差し込まれるであろうタグの高さを調整すればよろしいのですか？
![image](https://user-images.githubusercontent.com/52222236/79748631-bb363f80-8348-11ea-953b-f9bb0fb39f2c.png)

**Comment by tada00** [comment]
コラム一覧画像調整 #109
@eggsystem 
@tomo-ogiso 
すいません、こちら見てなくてコラムの一覧画面変更でコンポーネントごと変えたので #109 の修正で直っていると思うのですがどうでしょうか？

**Comment by eggsystem** [comment]
@tada00 
そうだね！
そっちで直ってるね。

こっちはクローズしよう。
