### ISSUE TITLE
ご依頼についてページ内の文字サイズ調整【優先度：高】

### ISSUE THREAD

**Issue by eggsystem** [egg-system/corporate-site#124]
当社サービスについての中の「サービス名」と「説明文」が同じサイズになってるので、説明文の文字サイズを小さくする。

**Comment by tada00** [comment]
@eggsystem 
「サービス名」と「説明文」両方pタグになっているのですが、「サービス名」をh5くらいに変更とかはしない方がいいでしょうか？

**Comment by eggsystem** [comment]
@tada00 
サービス名を「h3」で、文字サイズは今と同じで、よろしく。
h3にする理由はhtml構造上の話しね。（SEO対策という意味）
