### ISSUE TITLE
ニュース、コラム機能の実装

### ISSUE THREAD

**Issue by hikarut** [egg-system/corporate-site#34]
### 概要
* ニュース、コラム機能の実装

### 目的
* ニュース、コラムの投稿と参照ができるようにするため

### 対応内容
* microCMSを使って記事の投稿と参照ができるようにする
  * https://microcms.io/

**Comment by hikarut** [comment]
参考：microCMSのはじめ方
https://microcms.io/blog/getting-started/

**Comment by YUKI-AZUMA** [comment]
- アカウントはEGGSYSTEM共通の物を作成する
