### ISSUE TITLE
Netlifyの環境を移す

### ISSUE THREAD

**Issue by hikarut** [egg-system/corporate-site#52]
### 概要
* 現状はhikarutの個人アカウントに紐づいているのでエッグシステムで共通アカウント使ってそっちに移す

### 目的
* 個人に紐づけるのはよろしく無いので

### 対応内容
* エッグシステムでNetlifyのアカウント作成
  * https://www.netlify.com/
* そこにこのGitHubのリポジトリを紐付けする

**Comment by YUKI-AZUMA** [comment]
- 以下作業を実施しました。
- 現状不足があれば、教えていただけると幸いです🙏

- [ ] Netrifyで コーポレートサイトのリポジトリの設定
- [ ] 環境変数の設定

**Comment by eggsystem** [comment]
対応済
