### ISSUE TITLE
サービスページの改善（お問い合わせ欄の追加）【優先度：中】

### ISSUE THREAD

**Issue by eggsystem** [egg-system/corporate-site#85]
### 目的
* コンバージョン向上

### 対応内容
* サービスページの一番下にお問い合わせ欄を作る
* 載せる内容はトップページの「こんな相談してよいのか分からない・・・」のエリアと同じもの

**Comment by tomo-ogiso** [comment]
@eggsystem 
プルリク出したので、ご確認よろしくお願いします。

**Comment by tomo-ogiso** [comment]
@eggsystem こちらcloseします。
